[build]
  command = "#"
  functions = "functions"
  publish = "build"

[[plugins]]
  package = 'netlify-plugin-contextual-env'

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true