name: Test

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          retention-days: 5
          name: analyze
          path: packages/website/.next/analyze/**.html
