name: Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      PROD: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set COMMIT_MESSAGE env
        run: echo "COMMIT_MESSAGE=`git log -1 --pretty=format:"%s"`" >> $GITHUB_ENV

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build functions package
        run: yarn workspace functions build

      - name: Deploy to Netlify
        env:
          ALIAS: ${{ format('pr-{0}', github.event.number) }}
          PREVIEW_URL: ${{ format('https://{0}--wetter-vorchdorf-media.netlify.app', env.ALIAS) }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          if [[ $PROD == 'false' ]]; then
            yarn workspace website netlify build --context=deploy_preview
            yarn workspace website netlify deploy --alias=$ALIAS --message="$COMMIT_MESSAGE"
          else
            yarn workspace website netlify deploy --build --prod --message="$COMMIT_MESSAGE"
          fi

      - name: Release on GitHub
        if: ${{ env.PROD == 'true' }}
        run: npx semantic-release
